name: hotmapsDispatch
channels:
  - conda-forge
  - defaults
  - anaconda
  - bokeh
dependencies:
  - python=3.6
  - bokeh=0.12.10
  - numpy=1.16.2
  - pandas=0.24.2
  - openpyxl
  - xlrd   
  - matplotlib
  - pyomo=5.6.1
  - tornado=4
  - xlsxwriter
  - nodejs
  - altair
  - colorcet

  
 # open conda prompt here and type the following comand:
 # conda env create -f environment.yml
